dist: xenial
sudo: false

language: php
php:
  - '7.3'
  - 'nightly'

matrix:
  include:
    - language: node_js
      node_js:
        - 'stable'
        - 'lts/*'
      before_install:
        - 'node --version'
        - 'npm --version'
      install:
        - npm install
      cache:
        - $HOME/.npm
        - node_modules
  fast_finish: true
  allow_failures:
    - php: 'nightly'

cache:
  directories:
    - $HOME/.cache/composer
    - vendor

before_install:
  - sudo echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' >  /etc/apt/sources.list.d/pgdg.list
  - curl -fsSL 'https://www.postgresql.org/media/keys/ACCC4CF8.asc' | sudo apt-key add -
  - sudo apt update
  - sudo apt upgrade -y
  - sudo apt install -y brotli diffutils g++ gearman git graphicsmagick-imagemagick-compat jpegoptim make patch postgresql-11 postgresql-client-11 supervisor unzip
  - sudo /etc/init.d/postgresql start 11
  - sudo -u postgres createuser statink
  - sudo -u postgres psql -c 'ALTER USER statink WITH PASSWORD '\''statink'\'''
  - sudo -u postgres createdb --locale=C.UTF-8 --encoding=UTF8 --owner=statink statink

before_script:
  - composer --version
  - composer self-update
  - composer --version
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - cp `which composer` composer.phar

script:
  - make check-syntax
  - make init -j 4
  - ./yii secret/db localhost statink
  - make -j 4
